type = "NEG"

[[layer]]
color = "B"
grain_radius = 0.02
grain_sigma = 0.00
sigma_filter = 0.08

[[layer]]
color = "G"
grain_radius = 0.02
grain_sigma = 0.00
sigma_filter = 0.08

[[layer]]
color = "R"
grain_radius = 0.02
grain_sigma = 0.00
sigma_filter = 0.08
